version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

#  gateway:
#    image: gateway:latest
#    ports:
#      - "80:80"
#    depends_on:
#      - mongodb

  user-service:
    image: user-service:latest
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  training-table-service:
    image: training-table-service:latest
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  calendar-service:
    image: calendar-service:latest
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # Y así sucesivamente para cada servicio que tengas.
